let quote = document.getElementById("quote");
let btn = document.getElementById("btn");
const quotes = [
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Act as if what you do makes a difference. It does. - William James",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
  "Dream bigger. Do bigger. - Unknown",
  "Don’t stop when you’re tired. Stop when you’re done. - Unknown",
  "Wake up with determination. Go to bed with satisfaction. - Unknown",
  "Do something today that your future self will thank you for. - Unknown",
  "Little things make big days. - Unknown",
  "It’s going to be hard, but hard does not mean impossible. - Unknown",
  "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The best revenge is massive success. - Frank Sinatra",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Success is not just about making money. It’s about making a difference. - Unknown",
  "The key to success is to focus on goals, not obstacles. - Unknown",
  "Success is the result of perfection, hard work, learning from failure, loyalty, and persistence. - Colin Powell",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing. - Pelé",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Success is the progressive realization of a worthy goal or ideal. - Earl Nightingale",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25! 🤓", 
  "Why do programmers prefer dark mode? Because light attracts bugs! 🐛", 
  "Why don't programmers like nature? It has too many bugs! 🐞", 
  "Why did the programmer quit his job? He didn't get arrays! 😂", 
  "Why do programmers hate coffee breaks? Because they turn into 'Java' breaks! ☕", 
];

function getQuote() {
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  quote.innerHTML = randomQuote;
}